schema_version = "1.0.0"
id = "io_scene_max"
name = "Import Autodesk MAX (.max)"
version = "1.6.9"
tagline = "Import 3DSMAX meshes & materials"
maintainer = "NRG Sille <nrgsille@gmx.de>"
type = "add-on"
tags = ["Import-Export", "Mesh", "Material"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
website = "https://github.com/nrgsille76/io_scene_max"
copyright = [
	"2023-2024 Sebastian Schrand",
	"2017-2022 Jens M. Plonka",
	"2005-2018 Philippe Lagadec"
]
[permissions]
files = "Import Autodesk MAX files"


